core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'ERM Admin'
admin.site.index_title = 'Admin'
admin.site.site_title = 'ERM Admin'

urlpatterns = [
    path('', include('util.urls')),
    path('erm/', include('erm.urls')),
    path('note/', include('note.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

erm/urls.py
from django import views
from django.urls import path
from .views import *

app_name = 'erm'

urlpatterns = [
     path('product_list/', ProductListView.as_view(), name='product-list'),
     path('product_create/', ProductCreateView.as_view(), name='product-create'),
     path('product_detail/<int:pk>', ProductDetailView.as_view(), name='product-detail'),
     path('product_update/<int:pk>', ProductUpdateView.as_view(), name='product-update'),
     path('product_delete/<int:pk>', ProductDeleteView.as_view(), name='product-delete'),
     path('cost_list/', CostListView.as_view(), name='cost-list'),
     path('cost_create/', CostCreateView.as_view(), name='cost-create'),
     path('cost_detail/<int:pk>', CostDetailView.as_view(), name='cost-detail'),
     path('cost_update/<int:pk>', CostUpdateView.as_view(), name='cost-update'),
     path('cost_delete/<int:pk>', CostDeleteView.as_view(), name='cost-delete'),
     path('note_list/', notelist, name='notelist'),
     path('note_list/noteitemslist/<int:pk>', noteitemslist, name='noteitemslist'),
     path('note_list/noteitemslist_delete/<int:pk>', noteitemslist_delete, name='noteitemslist-delete'),
     path('note_list_rep/', notelistrep, name='notelist-rep'),
     # path('po/', POCreate, name='po-create'),
     #path('po_list/', POListView.as_view(), name='po-list'),
     #path('po_create/', poc, name='create-po'),
     #path('htmx/poitem-form/', create_poitem_form, name="poitem-form"),
     #path('htmx/poitem/<int:pk>/', detail_poitem, name="detail-poitem"),
     #path('htmx/poitem/<int:pk>/delete/', delete_poitem, name="delete-poitem"),
     #path('htmx/poitem/<int:pk>/update/', update_poitem, name="update-poitem"),
     #path('<int:pk>/', create_poitem, name="create-poitem"),
     # path('doc_list/', DocListView.as_view(), name='doc-list'),
     # path('doc_create/', doc_create, name='doc-create'),
     # path('docitem-form/', create_docitem_form, name="docitem-form"),
     # path('docitem/<int:pk>/', docitem_create, name="docitem-create"),
     # path('docitem/<int:pk>/detail', detail_docitem, name="detail-docitem"),
     # path('docitem/<int:pk>/list', docitem_list, name="list-docitem"),
     # path('docitem/<int:pk>/delete/', delete_docitem, name="delete-docitem"),
     # path('docitem/<int:pk>/update/', update_docitem, name="update-docitem"),
     
]

erm/forms.py
import collections
from dataclasses import fields
from datetime import datetime
from django import forms
from .customdatetime import minimalSplitDateTimeMultiWidget

from util.models import UserProfile
from note.models import Product, Cost
from .models import PurchaseOrder, PurchaseOrderItem
from django.forms.models import (
    modelform_factory,
    modelformset_factory,
    inlineformset_factory    
)

class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        template_name = "erm/product_list.html"
        fields = [
            'carat', 'product_name', 'buy_rate', 'sell_rate' 
        ]

class CostModelForm(forms.ModelForm):
    
    date = forms.DateTimeField(widget=minimalSplitDateTimeMultiWidget())

    class Meta:
        model = Cost
        template_name = "erm/cost_list.html"
        fields = [
            'carat', 'date', 'cost' 
        ]

class POForm(forms.ModelForm):
    class Meta:
        model = PurchaseOrder
        fields = (
            'purchase_order_id',
            'supplier',
        )        
class POModelForm(forms.Form):
    class Meta:
        fields = (
            'purchase_order_id', 'supplier',
            'product', 'purchase_order_item_weight', 'purchase_order_item_cost'
        )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Geerate PO id here
        # poId=dict(Client.objects.values_list('clientName', 'id'))
        self.fields['poid'] = forms.CharField(label='Purchase Order Number', required=True)
        self.fields['supplier'] = forms.ModelChoiceField(label='Supplier', queryset=UserProfile.objects.all(), required=True)
        self.fields['product'] = forms.ModelChoiceField(label='Product', queryset=Product.objects.all(), required=True)
        self.fields['purchase_order_item_weight'] = forms.DecimalField(label='Item Weight', required=True)
        self.fields['purchase_order_item_cost'] = forms.DecimalField(label='Item Cost', required=True)

    def clean_fields_(self, *args, **kwargs):
        poid = self.cleaned_data.get('poid')
        supplier= self.cleaned_data.get('supplier')
        product= self.cleaned_data.get('product')
        errProcess = self.cleaned_data.get('errProcess')
        return errProcess

class POItemForm(forms.ModelForm):
    class Meta:
        model = PurchaseOrderItem
        fields = (
            'product', 'purchase_order_item_weight', 'purchase_order_item_cost'
        )

POItemsFormSet = inlineformset_factory(
    PurchaseOrder,
    PurchaseOrderItem,
    POItemForm,
    can_delete=False,
    min_num=1,
    extra=0,
)

erm/views.py
from multiprocessing import context
from django.http import HttpResponse
from django.shortcuts import redirect, render, reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from erm.models import Collection, PurchaseOrder, PurchaseOrderItem
from note.models import Product, Cost, Note, Noteitem, Notetype, Client, Location
from util.models import UserProfile
from django.db.models import Q, Count, Sum
from .forms import POItemsFormSet, ProductModelForm, CostModelForm, POItemForm, POForm, POModelForm
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

def notelist(request):
    notetypes = Notetype.objects.all()
    clients = Client.objects.all()
    locations = Location.objects.all()
    notes = None
    return render(request, 'erm/note_list.html', {'notes': notes, 'notetypes': notetypes, 'locations': locations, 'clients': clients })


def notelistrep(request):

    notes = None
    
    notetype = request.POST.get('notetype', '')
    client = request.POST.get('client', '')
    location = request.POST.get('location', '')

    my_dict = {'notetype': notetype, 'client': client, 'location': location}  # Your dict with fields
    or_condition = Q()
    for key, value in my_dict.items():
        if value:
            or_condition.add(Q(**{key: value}), Q.AND)

    query_set = Note.objects.filter(or_condition).annotate(p=Sum('noteitem__pcost'), w=Sum('noteitem__weight'))
    #QAr.objects.all().annotate(Count('qaerrors__dept')).filter(dept=1)
    return render(request, 'erm/notelist_data.html', {'notes': query_set})

def noteitemslist(request, pk):
    note = Note.objects.get(id=pk)
    noteitems = Noteitem.objects.filter(note_id=note.id)

    return render(request, 'erm/partials/noteitems_list_rep.html', {'note': note, 'noteitems': noteitems})

def noteitemslist_delete(request, pk):
    return HttpResponse()

class CostCreateView(LoginRequiredMixin, CreateView):
    template_name = "erm/cost_create.html"
    form_class = CostModelForm

    def get_success_url(self):
        return reverse("erm:cost-list") 

class CostListView(LoginRequiredMixin, ListView):
    template_name = "erm/cost_list.html"
    queryset = Cost.objects.all()

class CostDetailView(LoginRequiredMixin, DetailView):
    template_name = "erm/cost_detail.html"
    queryset = Cost.objects.all()
    form_class = CostModelForm

class CostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "erm/cost_update.html"
    queryset = Cost.objects.all()
    form_class = CostModelForm

    def get_success_url(self):
        return reverse("erm:cost-list") 

class CostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "erm/cost_delete.html"
    queryset = Cost.objects.all()

    def get_success_url(self):
        return reverse("erm:cost-list")

class ProductCreateView(LoginRequiredMixin, CreateView):
    template_name = "erm/product_create.html"
    form_class = ProductModelForm

    def get_success_url(self):
        return reverse("erm:product-list") 

class ProductListView(LoginRequiredMixin, ListView):
    template_name = "erm/product_list.html"
    queryset = Product.objects.all()

class ProductDetailView(LoginRequiredMixin, DetailView):
    template_name = "erm/product_detail.html"
    queryset = Product.objects.all()
    form_class = ProductModelForm

class ProductUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "erm/product_update.html"
    queryset = Product.objects.all()
    form_class = ProductModelForm

    def get_success_url(self):
        return reverse("erm:product-list") 

class ProductDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "erm/product_delete.html"
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse("erm:product-list")

''' class POCreateView(LoginRequiredMixin, CreateView):
    template_name = "erm/po_create.html"
    form_class = POForm

    def get_success_url(self):
        return reverse("erm:detail-poitem")
    
def poc(request):
    print(request.POST)
    form = POForm()
    if request.method == "POST":
        form = POForm(request.POST)
        if form.is_valid():
            poid  = form.cleaned_data['purchase_order_id']
            supplier = form.cleaned_data['supplier']
            obj_supplier = UserProfile.objects.get(user_id=supplier.id)
            PurchaseOrder.objects.get_or_create(
                purchase_order_id=poid,
                supplier=obj_supplier,
                # purchase_order_total_weight=purchase_order_item_weight,
                # purchase_order_total_items=1,
                # purchase_order_cost=purchase_order_item_cost,
            )
            return redirect("erm:create-poitem", pk=poid)
    context = {
        "form": form
    }
    return render(request, "erm/po_create.html", context)

class POListView(LoginRequiredMixin, ListView):
    template_name = "erm/doc-list.html"
    queryset = PurchaseOrder.objects.all()

  
def POCreate(request):
    print(request.POST)
    form = POModelForm()
    if request.method == 'POST':
        form = POModelForm(request.POST)
        if form.is_valid():
            poid = form.cleaned_data['poid']
            supplier = form.cleaned_data['supplier']
            product = form.cleaned_data['product']
            purchase_order_item_weight = form.cleaned_data['purchase_order_item_weight']
            purchase_order_item_cost = form.cleaned_data['purchase_order_item_cost']
            # obj_supplier = UserProfile.objects.get(id=supplier.id)
            obj_supplier = UserProfile.objects.get(user_id=supplier.id)
            obj_po, po_create = PurchaseOrder.objects.get_or_create(
                purchase_order_id=poid,
                supplier=obj_supplier,
                purchase_order_total_weight=purchase_order_item_weight,
                purchase_order_total_items=1,
                purchase_order_cost=purchase_order_item_cost,
            )
            
            obj_product = Product.objects.get(product_id=product.product_id)
            PurchaseOrderItem.objects.create(
                purchase_order=obj_po,
                product=obj_product,
                purchase_order_item_weight=purchase_order_item_weight,
                purchase_order_item_cost=purchase_order_item_cost,
            )
            return redirect("erm:create-poitem", pk=poid)
    context = {
        "form": form
    }
    return render(request, "erm/po_head.html", context)
 '''
# class POCreateView(LoginRequiredMixin, CreateView):
#     template_name = "erm/po_create.html"
#     form_class = POForm

#     def get_success_url(self):
#         return reverse("erm:product-list") 

# def create_po(request):
#     form = POModelForm(request.POST or None)
    
#     if request.method == "POST":
#         if form.is_valid():
#             po = form.save(commit=False)
#             po.purchase_order = po
#             po.save()
#             return redirect("erm:detail-poitem", pk=po.id)
    
#     context = {
#         "form": form,
#     }
    
#     return render(request, "erm/create_po.html", context)

''' def create_poitem(request, pk):
    po = PurchaseOrder.objects.get(purchase_order_id=pk)
    poitems = PurchaseOrderItem.objects.filter(purchase_order=po)
    form = POItemForm(request.POST or None)
    
    if request.method == "POST":
        if form.is_valid():
            poitem = form.save(commit=False)
            poitem.purchase_order = po
            poitem.save()
            return redirect("erm:detail-poitem", pk=poitem.id)
        else:
            return render(request, "erm/partials/poitem_form.html", {"form": form})
    
    context = {
        "form": form,
        "po": po,
        "poitem": poitems
    }
    
    return render(request, "erm/create_poitem.html", context)

def create_poitem_form(request):
    print("create_poitem_form" , request.POST)
    context = {
        "form": POItemForm()
    }
    return render(request, "erm/partials/poitem_form.html", context)

def detail_poitem(request, pk):
    print("detail_poitem", request)
    poitem = PurchaseOrderItem.objects.get(pk=pk)
    context = {
        "poitem": poitem
        }
    return render(request, "erm/partials/poitem_detail.html", context)

def delete_poitem(request, pk):
    poitem = PurchaseOrderItem.objects.get(pk=pk)
    poitem.delete()
    #return HttpResponse('')
    return render(request, "erm/create_poitem.html", context)

def update_poitem(request, pk):
    poitem = PurchaseOrderItem.objects.get(pk=pk)
    form = POItemForm(request.POST or None, instance=poitem)
    
    if request.method == "POST":
        if form.is_valid():
            poitem.save()
            return redirect("erm:detail-poitem", pk=poitem.id)
    
    context = {
        "form": form,
        "poitem": poitem
    }
    return render(request, "erm/partials/poitem_form.html", context)

class DocListView(LoginRequiredMixin, ListView):
    template_name = "erm/doc-list.html"
    queryset = PurchaseOrder.objects.all()
    
def create_docitem_form(request):
    print("create_docitem_form" , request.POST)
    context = {
        "form": POItemForm()
    }
    return render(request, "erm/partials/docitem_form.html", context)
    
def detail_docitem(request, pk):
    print("detail_docitem", request)
    poitem = PurchaseOrderItem.objects.get(pk=pk)
    context = {
        "poitem": poitem
        }
    return render(request, "erm/partials/docitem_detail.html", context)

def delete_docitem(request, pk):
    poitem = PurchaseOrderItem.objects.get(pk=pk)
    poitem.delete()
    #return HttpResponse('')
    #return render(request, "erm/create_docitem.html", context)
    return redirect("erm:list-docitem", pk=poitem.purchase_order_id)


def update_docitem(request, pk):
    poitem = PurchaseOrderItem.objects.get(pk=pk)
    form = POItemForm(request.POST or None, instance=poitem)
    
    if request.method == "POST":
        if form.is_valid():
            poitem.save()

templates/erm/cost_create.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 mx-auto">
    <div class="max-w-lg mx-auto">
      <div class="max-w-lg mx-auto">
        <h1 class="text-4xl text-gray-800">Cost Create</h1>
      </div>
      <div class="py-5 border-b border-gray-200">
        <a
          class="hover:text-blue-500"
          href="{% url 'erm:product-list' %}"
          rel="noopener noreferrer"
          >Cost List</a
        >
      </div>
      <form method="post" class="mt-3 mb-3">
        {% csrf_token %} {{form|crispy}}
        <button
          type="submit"
          class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md"
        >
          Create
        </button>
      </form>
    </div>
  </div>
</section>
{% endblock content %}

templates/erm/cost_detail.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-2 mx-auto">
    <div class="max-w-lg mx-auto">
      <div class="max-w-lg mx-auto">
        <h1 class="text-2xl text-gray-800">
          Cost - {{ cost.carat }}
        </h1>
      </div>
      <div class="py-5 border-b border-gray-200">
        <a
          class="hover:text-blue-500"
          href="{% url 'erm:cost-list' %}"
          rel="noopener noreferrer"
          >Cost List</a
        >
      </div>

      <div class="flex border-t border-b mb-6 border-gray-200 py-2">
        <span class="text-gray-500">Carat</span>
        <span class="ml-auto text-gray-900">{{ cost.carat }}</span>
      </div>
      <div class="flex border-t border-b mb-6 border-gray-200 py-2">
        <span class="text-gray-500">Date</span>
        <span class="ml-auto text-gray-900">{{ cost.date }}</span>
      </div>
      <div class="flex border-t border-b mb-6 border-gray-200 py-2">
        <span class="text-gray-500">Cost</span>
        <span class="ml-auto text-gray-900">{{ cost.cost }}</span>
      </div>
      <div class="mt-2 py-2 border-t border-gray-200">
        <a
          href="{% url 'erm:cost-update' cost.id %}"
          class="flex w-full text-white justify-center bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          >Update</a
        >
      </div>
      <div class="mt-2 py-2 border-t border-gray-200">
        <a
          href="{% url 'erm:cost-delete' cost.id %}"
          class="flex w-full text-white justify-center bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded"
          >Delete</a
        >
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/erm/cost_list.html
{% extends "base.html" %} {% block content %}
{% load tz %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-2 mx-auto">
    <a href="{% url 'erm:cost-create' %}">Create Product</a>
    <hr />
    <div class="flex flex-col text-center w-full mb-20">
      <h1
        class="sm:text-4xl text-2xl font-medium title-font mt-2 mb-2 text-gray-900"
      >
        Cost List
      </h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
        Registered list as of {% now "jS F Y H:i" %}
      </p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl"
            >
              Carat
            </th>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
            >
              date
            </th>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
            >
              Cost
            </th>            
          </tr>
        </thead>
        {% if object_list %} {% for cost in object_list %}
        <tbody>
          <tr>
            <td class="px-4 py-3">
              <a href="{% url 'erm:cost-detail' cost.id %}">
                {{ cost.carat }}
              </a>
            </td>
            <td class="px-4 py-3">{{ cost.carat }}</td>
            <td class="px-4 py-3">{{ cost.date|localtime }}</td>
            <td class="px-4 py-3">{{ cost.cost }}</td>
          </tr>
        </tbody>
        {% endfor %} {% else %}
        <p>There are no cost to display.</p>
        {% endif %}
      </table>
    </div>
    <div class="flex pl-4 mt-4 lg:w-2/3 w-full mx-auto">
      <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0"
        >More
        <svg
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          class="w-4 h-4 ml-2"
          viewBox="0 0 24 24"
        >
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    </div>
  </div>
</section>

{% endblock content %}

templates/erm/doc-list.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-2 mx-auto">
    <a href="{% url 'erm:doc-create' %}">Create Doc</a>
    <hr />
    <div class="flex flex-col text-center w-full mb-20">
      <h1
        class="sm:text-4xl text-2xl font-medium title-font mt-2 mb-2 text-gray-900"
      >
        Doc List
      </h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
        Registered list as of 31 December 2020
      </p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl"
            >
              Date
            </th>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
            >
              Supplier
            </th>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
            >
              Re-order Level
            </th>
            <th
              class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"
            ></th>
          </tr>
        </thead>
        {% if object_list %} {% for po in object_list %}
        <tbody>
          <tr>
            <td class="px-4 py-3">
              {% comment %} <a href="{% url 'erm:product-detail' product.product_id %}"> {% endcomment %}
                {{ po.purchase_order_id }}
              </a>
            </td>
            <td class="px-4 py-3">{{ po.date }}</td>
            <td class="px-4 py-3">{{ po.supplier }}</td>

            <td class="w-10 text-center">
              <input name="plan" type="radio" />
            </td>
          </tr>
        </tbody>
        {% endfor %} {% else %}
        <p>There are no purchase to display.</p>
        {% endif %}
      </table>
    </div>
    <div class="flex pl-4 mt-4 lg:w-2/3 w-full mx-auto">
      <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0"
        >More
        <svg
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          class="w-4 h-4 ml-2"
          viewBox="0 0 24 24"
        >
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    </div>
  </div>
</section>

{% endblock content %}

templates/erm/note_detail.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
# Annotate sample
# context['q0'] = QAr.objects.all().annotate(Count('qaerrors__dept')).filter(dept=1)
#
<section class="text-gray-600 body-font">
  <div class="container px-5 py-2 mx-auto">
    <div class="max-w-lg mx-auto">
      <div class="max-w-lg mx-auto">
        <h1 class="text-2xl text-gray-800">
          Cost - {{ cost.carat }}
        </h1>
      </div>
      <div class="py-5 border-b border-gray-200">
        <a
          class="hover:text-blue-500"
          href="{% url 'erm:cost-list' %}"
          rel="noopener noreferrer"
          >Cost List</a
        >
      </div>

      <div class="flex border-t border-b mb-6 border-gray-200 py-2">
        <span class="text-gray-500">Carat</span>
        <span class="ml-auto text-gray-900">{{ cost.carat }}</span>
      </div>
      <div class="flex border-t border-b mb-6 border-gray-200 py-2">
        <span class="text-gray-500">Date</span>
        <span class="ml-auto text-gray-900">{{ cost.date }}</span>
      </div>
      <div class="flex border-t border-b mb-6 border-gray-200 py-2">
        <span class="text-gray-500">Cost</span>
        <span class="ml-auto text-gray-900">{{ cost.cost }}</span>
      </div>
      <div class="mt-2 py-2 border-t border-gray-200">
        <a
          href="{% url 'erm:cost-update' cost.id %}"
          class="flex w-full text-white justify-center bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          >Update</a
        >
      </div>
      <div class="mt-2 py-2 border-t border-gray-200">
        <a
          href="{% url 'erm:cost-delete' cost.id %}"
          class="flex w-full text-white justify-center bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded"
          >Delete</a
        >
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/erm/notelist_data.html
      <div class="divide-y divide-gray-200" id="notes">
        {% for note in notes %} {% include 'erm/partials/note_list_rep.html' %} {%endfor %}
      </div>

templates/erm/product_list.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-2 mx-auto">
    <a href="{% url 'erm:product-create' %}">Create Product</a>
    <hr />
    <div class="flex flex-col text-center w-full mb-20">
      <h1
        class="sm:text-4xl text-2xl font-medium title-font mt-2 mb-2 text-gray-900"
      >
        Product List
      </h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
        Registered list as of 31 December 2020
      </p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl"
            >
              Description
            </th>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
            >
              Collection
            </th>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
            >
              Re-order Level
            </th>
            <th
              class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"
            ></th>
          </tr>
        </thead>
        {% if object_list %} {% for product in object_list %}
        <tbody>
          <tr>
            <td class="px-4 py-3">
              <a href="{% url 'erm:product-detail' product.product_id %}">
                {{ product.description }}
              </a>
            </td>
            <td class="px-4 py-3">{{ product.collection }}</td>
            <td class="px-4 py-3">{{ product.reorder_level }}</td>

            <td class="w-10 text-center">
              <input name="plan" type="radio" />
            </td>
          </tr>
        </tbody>
        {% endfor %} {% else %}
        <p>There are no product to display.</p>
        {% endif %}
      </table>
    </div>
    <div class="flex pl-4 mt-4 lg:w-2/3 w-full mx-auto">
      <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0"
        >More
        <svg
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          class="w-4 h-4 ml-2"
          viewBox="0 0 24 24"
        >
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    </div>
  </div>
</section>

{% endblock content %}