core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'ERM Admin'
admin.site.index_title = 'Admin'
admin.site.site_title = 'ERM Admin'

urlpatterns = [
    path('', include('util.urls')),
    path('erm/', include('erm.urls')),
    path('note/', include('note.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

erm/urls.py
from django import views
from django.urls import path
from .views import *

app_name = 'erm'

urlpatterns = [
     path('product_list/', ProductListView.as_view(), name='product-list'),
     path('product_create/', ProductCreateView.as_view(), name='product-create'),
     path('product_detail/<int:pk>', ProductDetailView.as_view(), name='product-detail'),
     path('product_update/<int:pk>', ProductUpdateView.as_view(), name='product-update'),
     path('product_delete/<int:pk>', ProductDeleteView.as_view(), name='product-delete'),
     path('cost_list/', CostListView.as_view(), name='cost-list'),
     path('cost_create/', CostCreateView.as_view(), name='cost-create'),
     path('cost_detail/<int:pk>', CostDetailView.as_view(), name='cost-detail'),
     path('cost_update/<int:pk>', CostUpdateView.as_view(), name='cost-update'),
     path('cost_delete/<int:pk>', CostDeleteView.as_view(), name='cost-delete'),
     path('note_list/', notelist, name='notelist'),
     path('note_list/noteitemslist/<int:pk>', noteitemslist, name='noteitemslist'),
     path('note_list/noteitemslist_delete/<int:pk>', noteitemslist_delete, name='noteitemslist-delete'),
     path('note_list_rep/', notelistrep, name='notelist-rep'),
     # path('po/', POCreate, name='po-create'),
     #path('po_list/', POListView.as_view(), name='po-list'),
     #path('po_create/', poc, name='create-po'),
     #path('htmx/poitem-form/', create_poitem_form, name="poitem-form"),
     #path('htmx/poitem/<int:pk>/', detail_poitem, name="detail-poitem"),
     #path('htmx/poitem/<int:pk>/delete/', delete_poitem, name="delete-poitem"),
     #path('htmx/poitem/<int:pk>/update/', update_poitem, name="update-poitem"),
     #path('<int:pk>/', create_poitem, name="create-poitem"),
     # path('doc_list/', DocListView.as_view(), name='doc-list'),
     # path('doc_create/', doc_create, name='doc-create'),
     # path('docitem-form/', create_docitem_form, name="docitem-form"),
     # path('docitem/<int:pk>/', docitem_create, name="docitem-create"),
     # path('docitem/<int:pk>/detail', detail_docitem, name="detail-docitem"),
     # path('docitem/<int:pk>/list', docitem_list, name="list-docitem"),
     # path('docitem/<int:pk>/delete/', delete_docitem, name="delete-docitem"),
     # path('docitem/<int:pk>/update/', update_docitem, name="update-docitem"),
     
]

note/urls.py
from django.urls import path

from note.views import init, notes, noteitems, add_note, update_note, delete_note, add_noteitem, update_noteitem, delete_noteitem, edit_noteitem, invlist, icost

app_name = 'note'

urlpatterns = [
    path('', init, name='init'),
    path('notes/', notes, name='notes'),
    path('add-note/', add_note, name='add_note'),       
    path('update_note/<int:pk>/', update_note, name='update_note'),
    path('delete_note/<int:pk>/', delete_note, name='delete_note'),
    path('noteitems/<int:pk>/', noteitems, name='noteitems'),
    path('<int:note>/add-noteitem/', add_noteitem, name='add_noteitem'),
    path('update_noteitem/<int:pk>/', update_noteitem, name='update_noteitem'),
    path('delete_noteitem/<int:pk>/', delete_noteitem, name='delete_noteitem'),
    path('edit_noteitem/<int:pk>/', edit_noteitem, name='edit_noteitem'),
    path('invlist/<int:pk>/', invlist, name='invlist'),
    # path('invdata/', invdata, name='invdata'),
    # path('val_cost/', val_cost, name='val_cost'),
    # path('val_qty/', val_qty, name='val_qty'),
    path('icost/<int:pk>/', icost, name='icost'),
]

note/views.py
from operator import gt
from django.shortcuts import render
from django.http.response import HttpResponse
from django.views.decorators.http import require_http_methods

from django.core.serializers import serialize
from django.http import JsonResponse
from json import loads
from decimal import Decimal
from datetime import datetime
from django.utils import timezone
from django.db.models import Q

from .models import Client, Cost, Note, Noteitem, Location, Notekey, Notetype, Status, Noteitemkey, PO, POItem, PR, PRItem, Product, SO, SOItem, SR, SRItem, CO, COItem, WI, WR, WIItem, WRItem, Inv, InvControl, WorkInvControl

def notes(request):
    
    notes = None
    
    notetype = request.GET.get('notetype', '')
    client = request.GET.get('client', '')
    location = request.GET.get('location', '')

    # One day old notes not displayed
    
    # creationDate = datetime.datetime.now()
    todayDate = timezone.now()
    
    if notetype or client:
        if notetype and client and location:
            notes = Note.objects.filter(notetype_id=notetype, created_on__date=todayDate, client_id=client, location_id=location)
        if notetype and client and location:
            notes = Note.objects.filter(notetype_id=notetype, created_on__date=todayDate, client_id=client, location_id=location)
        if notetype and client=='' and location =='':
            notes = Note.objects.filter(notetype_id=notetype, created_on__date=todayDate)
        if notetype and location and client=='':
            notes = Note.objects.filter(notetype_id=notetype, created_on__date=todayDate, location_id=location)
        if notetype and location=='' and client:
            notes = Note.objects.filter(notetype_id=notetype, created_on__date=todayDate, client_id=client)
        if notetype=="" and client:
            notes = Note.objects.filter(client_id=client, created_on__date=todayDate)
        if notetype=="" and client and location:
            notes = Note.objects.filter(client_id=client, created_on__date=todayDate, location_id=location)
        #return render(request, 'note/notes.html', {'notes': notes, 'notetypes': notetypes, 'clients': clients, 'locations': locations, 's_notetype': s_notetype})
    
    return render(request, 'note/notes.html', {'notes': notes})

    
''' def notes(request):
    
    selected = {}
    notes = None
    client = None
    location = None
    s_notetype = None
    
    if request.method == 'GET':
        s_notetype = request.GET.get('notetype', '')
        client = request.GET.get('client', '')
        location = request.GET.get('location', '')

        selected['client']=client
        selected['location']=location
        selected['notetype']=s_notetype
    
        if s_notetype or client:
            if s_notetype and client and location:
                notes = Note.objects.filter(notetype_id=s_notetype, client_id=client, location_id=location)
            if s_notetype and client=="":
                notes = Note.objects.filter(notetype_id=s_notetype)
            if s_notetype and location and client=="":
                notes = Note.objects.filter(notetype_id=s_notetype, location_id=location)
            if s_notetype=="" and client:
                notes = Note.objects.filter(client_id=client)
            if s_notetype=="" and client and location:
                notes = Note.objects.filter(client_id=client, location_id=location)
            #return render(request, 'note/notes.html', {'notes': notes, 'notetypes': notetypes, 'clients': clients, 'locations': locations, 's_notetype': s_notetype})
            return render(request, 'note/notes.html', {'notes': notes})

    notetypes = Notetype.objects.all()
    clients = Client.objects.all()
    locations = Location.objects.all()

    return render(request, 'note/init.html', {'notes': notes, 'notetypes': notetypes, 'clients': clients, 'locations': locations, 's_notetype': s_notetype, 'selected': selected})
 '''
def init(request):
    notetypes = Notetype.objects.all()
    clients = Client.objects.all()
    locations = Location.objects.all()
    notes = None
    return render(request, 'note/init.html', {'notes': notes, 'notetypes': notetypes, 'locations': locations, 'clients': clients })

@require_http_methods(['POST'])
def add_note(request):
    note = None
    obj_note = None
    notetype = request.POST.get('notetype', '')
    location = request.POST.get('location', '')
    notekey = request.POST.get('notekey', '')
    client = request.POST.get('client', '')
    
    my_dict = {'notetype': notetype, 'client': client, 'location': location, 'notekey': notekey}  # Your dict with fields
    msg=""
    for key, value in my_dict.items():
        if value=="":
            msg=msg + key + " "
        
    if notekey and notetype!=None and client:
        obj_notetype = Notetype.objects.get(id=notetype)
        obj_notekey, create_notekey = Notekey.objects.get_or_create(notekey=notekey)
        obj_client = Client.objects.get(id=client)
        
        if obj_notetype.id == 1:
            obj_po, create_po = PO.objects.get_or_create(notekey=obj_notekey, notetype=obj_notetype, typ=obj_notetype.id, client=obj_client)
            obj_note = Note.objects.get(id=obj_po.note_ptr_id)

        if obj_notetype.id == 11:
            obj_po, create_po = PR.objects.get_or_create(notekey=obj_notekey, notetype=obj_notetype, typ=obj_notetype.id, client=obj_client)
            obj_note = Note.objects.get(id=obj_po.note_ptr_id)

        if obj_notetype.id == 2:
            obj_so, create_so = SO.objects.get_or_create(notekey=obj_notekey, notetype=obj_notetype, typ=obj_notetype.id, client=obj_client)
            obj_note = Note.objects.get(id=obj_so.note_ptr_id)

        if obj_notetype.id == 12:
            obj_so, create_so = SR.objects.get_or_create(notekey=obj_notekey, notetype=obj_notetype, typ=obj_notetype.id, client=obj_client)
            obj_note = Note.objects.get(id=obj_so.note_ptr_id)

        if obj_notetype.id == 3:
            obj_co, create_po = CO.objects.get_or_create(notekey=obj_notekey, notetype=obj_notetype, typ=obj_notetype.id, client=obj_client)
            obj_note = Note.objects.get(id=obj_co.note_ptr_id)

        if obj_notetype.id == 4:
            obj_wo, create_so = WI.objects.get_or_create(notekey=obj_notekey, notetype=obj_notetype, typ=obj_notetype.id, client=obj_client)
            obj_note = Note.objects.get(id=obj_wo.note_ptr_id)

        if obj_notetype.id == 14:
            obj_wo, create_so = WR.objects.get_or_create(notekey=obj_notekey, notetype=obj_notetype, typ=obj_notetype.id, client=obj_client)
            obj_note = Note.objects.get(id=obj_wo.note_ptr_id)
                   
    return render(request, 'note/partials/note.html', {'note': obj_note, 'msg': msg})

@require_http_methods(['GET', 'POST'])
def edit_note(request, pk):
    note = Note.objects.get(pk=pk)

    if request.method == 'POST':
        note.notetype = request.POST.get('notetype', '')
        note.save()

        return render(request, 'note/partials/note.html', {'note': note})
    
    return render(request, 'note/partials/edit_note.html', {'note': note})

@require_http_methods(['PUT'])
def update_note(request, pk):

    note = Note.objects.get(id=pk)
    status = Status.objects.get(id=2)
    
    note.is_final = True
    note.status = status
    note.save()

    return render(request, 'note/partials/note.html', {'note': note})

@require_http_methods(['DELETE'])
def delete_note(request, pk):
    
    note = Note.objects.get(id=pk)
    
    note.delete()

    return HttpResponse()


def noteitems(request, pk):
    #notekey = Notekey.objects.get(notekey=noteref)
    note = Note.objects.get(id=pk)
    invlist=None
    message=None

    products = Product.objects.all()
    noteref = note.notekey_id
    noteitems = Noteitem.objects.filter(notekey_id=noteref, notetypekey_id=note.notetype_id)

    # if note.notetype_id==1 and request.method == 'GET' and request.GET.get('product', ''):
    #     invlist = Inv.objects.filter(product_id=request.GET.get('product', ''))

    #note = Note.objects.filter(notekey_id=notekey)[:1].get()

    return render(request, 'note/noteitems.html', {'noteref': noteref, 'noteitems': noteitems, 'note': note, 'products': products, 'invlist': invlist, 'message' : message})

@require_http_methods(['GET', 'POST'])
def invlist(request, pk):
    message=None
    note = Note.objects.get(id=pk)
    #invlist = Inv.objects.filter(product_id=request.GET.get('product', ''))
    product=request.GET.get('product', '')
    prodcost=request.GET.get('prodcost', '')
    weight=request.GET.get('weight', '')
    qty=request.GET.get('qty', '')
    if weight=='':
        weight=1
    if qty=='':
        qty=1
    obj_product=Product.objects.get(pk=product)
    invlist = InvControl.objects.filter(product_id=request.GET.get('product', ''), inventory__gt =0 )
    cost=Cost.objects.filter(carat_id=obj_product.carat_id).first()
    rate=obj_product.sell_rate
    if note.notetype.id == 1:
        rate=obj_product.buy_rate
    prodcost=cost.cost+(cost.cost/100*rate)
    icost=prodcost*qty*weight
    return render(request, 'note/invlist.html', {'note': note, 'invlist':invlist, 'message' : message, 'prodcost' : prodcost, 'weight': weight, 'qty': qty, 'icost': icost})

# @require_http_methods(['GET', 'POST'])
# def invdata(request):
#     message=None
#     weight = request.POST.get('weight', '')
#     quantity = request.POST.get('quantity', '')
#     if '-' in weight:
#         s_invitem = weight.split('-')[2]
#         obj_invcontrol=InvControl.objects.get(id=s_invitem)
#         if int(quantity) > obj_invcontrol.inventory:
#             message = "Maximum Quantity exceeded"
#     #return HttpResponse(error)
#     return render(request, 'note/partials/message.html', {'message': message})

# @require_http_methods(['GET', 'POST'])
# def val_qty(request):
#     message=None
#     weight = request.POST.get('weight', '')
#     qty = request.POST.get('qty', '')

templates/note/init copy.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
  <section class="text-gray-600 body-font">
      <div id="main" class="w-9/10 my-6 mx-auto p-2 lg:p-10 bg-white rounded-xl" >
        <form
          class="flex mb-6 space-x-4"
          hx-post="{% url 'note:add_note' %}"
          hx-target="#notes"
          hx-swap="afterend"
        >

          <select
          id="notetypelist" name="notetype" placeholder="NoteType" class="note flex-1 px-4 py-3 bg-gray-200 rounded-xl"
            hx-get="notes{{ notetype.id }}/"
            hx-trigger="change"
            hx-target="#notes"
            hx-swap="outerHTML"/>
            <option value="">Note Type</option>
          {% for notetype in notetypes %}
            <option value="{{ notetype.id}}">{{ notetype }}</option>
          {% endfor %}
          </select>

          <select
          id="locationlist" name="location" placeholder="Location" class="note flex-1 px-4 py-3 bg-gray-200 rounded-xl"/>
          <option value="">Location</option>
          {% for loc in locations %}
            <option value="{{ loc.id}}">{{ loc }}</option>
          {% endfor %}
          </select>

          <select
          id="clientlist" name="client" placeholder="Client" class="note flex-1 px-4 py-3 bg-gray-200 rounded-xl"
            hx-get="notes{{ client.id }}/"
            hx-trigger="change"
            hx-target="#notes"
            hx-swap="outerHTML"/>
          <option value="">Client</option>
          {% for client in clients %}
            <option value="{{ client.id}}">{{ client }}</option>
          {% endfor %}
          </select>

          <input
            type="text"
            name="notekey"
            class="title flex-1 px-4 py-3 bg-gray-200 rounded-xl"
            placeholder="Note #"
          />
          <button class="p-3 rounded-xl text-white bg-gray-400 hover:bg-gray-600">
            +
          </button>
        </form>

        <div class="flex py-3 rounded-xl bg-gray-100">
          <div class="w-4/5">
            <p class="px-6 text-xs font-medium text-gray-500 uppercase">Title</p>
          </div>
          <div class="w-4/5" id="message" hx-swap-oob="true" >
          {% if message is not None %}
              <p class ="px-6 text-xs font-medium text-gray-500 uppercase">{{message}}</p>
          {% endif %}
          </div>
          <div class="hidden md:block w-1/5 px-6 text-right">
            <p class="text-xs font-medium text-gray-500 uppercase">Actions</p>
          </div>
        </div>

        <div class="divide-y divide-gray-200" id="notes">
          {% for note in notes %} {% include 'note/partials/note.html' %} {%endfor %}
        </div>
      </div>
  </section>
{% endblock content %}

templates/note/init.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
  <section class="text-gray-600 body-font">

    <!-- <div id="main" class="w-9/10 my-6 mx-auto p-2 lg:p-10 bg-white rounded-xl" > -->
          <!-- class="flex mb-6 mt-6 space-x-4" -->
      <div id="main">
        <form class="w-9/10 my-1 mx-auto p-1 lg:p-5 bg-white rounded-xl"
            hx-post="{% url 'note:add_note' %}"
            hx-target="#notes"
            hx-swap="afterend"
          >

        <div class="flex flex-wrap -mx-3 mb-6 mt-6 space-x-4">
            <div class="mb-4">
              <label class="block text-gray-700 text-sm font-bold mb-2" for="notetypelist">
                Note Type
              </label>
              <select
              label="Note Type"
              id="notetypelist" name="notetype" placeholder="NoteType" class="note flex-1 px-4 py-3 bg-gray-200 rounded-xl"
                hx-get="notes{{ notetype.id }}/"
                hx-trigger="change"
                hx-target="#notes"
                hx-swap="outerHTML"/>
                <option value="">Note Type</option>
              {% for notetype in notetypes %}
                <option value="{{ notetype.id}}">{{ notetype }}</option>
              {% endfor %}
              </select>
            </div>

          <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="locationlist">
              Location
            </label>
            <select
            id="locationlist" name="location" placeholder="Location" class="note flex-1 px-4 py-3 bg-gray-200 rounded-xl"/>
            <option value="">Location</option>
            {% for loc in locations %}
              <option value="{{ loc.id}}">{{ loc }}</option>
            {% endfor %}
            </select>
          </div>

          <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="clientlist">
              Client
            </label>        
            <select
            id="clientlist" name="client" placeholder="Client" class="note flex-1 px-4 py-3 bg-gray-200 rounded-xl"
              hx-get="notes{{ client.id }}/"
              hx-trigger="change"
              hx-target="#notes"
              hx-swap="outerHTML"/>
            <option value="">Client</option>
            {% for client in clients %}
              <option value="{{ client.id}}">{{ client }}</option>
            {% endfor %}
            </select>
          </div>

          <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="trans">
              Transaction No
            </label>        
            <input
              id="trans"
              type="text"
              name="notekey"
              class="title flex-1 px-4 py-3 bg-gray-200 rounded-xl"
              placeholder="Note #"
            />
          </div>

          <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="add">
              Add
            </label>  
            <button class="p-3 rounded-xl text-white bg-gray-400 hover:bg-gray-600">
              +
            </button>
          </div>

        </div>
        </form>

        <div class="lg:w-3/3 w-full mx-auto overflow-auto">
          <table class="table-auto w-full text-left whitespace-no-wrap">
            <thead>
              <tr>
                <th
                  class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl"
                >
                  Location
                </th>
                <th
                  class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
                >
                  Client
                </th>
                <th
                  class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
                >
                  Transaction #
                </th>            
                <th
                  class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
                >
                  Date & Time
                </th>
              </tr>
            </thead>
        </table>
        </div>


        <div class="divide-y divide-gray-200" id="notes">
            {% if notes %} 
            {% for note in notes %} {% include 'note/partials/note.html' %} {%endfor %}
  
            {% else %}
              <p>There are no notes to display.</p>
            {% endif %}
        </div>

      </div>
    </section>
    {% endblock content %}

templates/note/invdata.html
     <input
        id="invdata"
        type="number"
        name="quantity"
        min="1"
        max="{{invdata.inventory}}"
        class="title flex-1 px-4 py-3 bg-gray-200 rounded-xl"
        placeholder="quantity"
      />      
      <input
        type="number"
        max="{{invdata.cost}}"
        name="cost"
        step=".01"
        class="title flex-1 px-4 py-3 bg-gray-200 rounded-xl"
        placeholder="cost"
      />

templates/note/noteitems.html
<div id="noteitems">
  <div class="flex mb-2 space-x-4 w-6/7 my-1 mx-auto p-2 lg:p-1 bg-white rounded-xl">
     <div class="mb-4">
      <label class="block text-gray-700 text-sm font-normal mb-3" for="note">
        TRANSACTION
      </label>  
      <label class="note flex-1 px-4 py-3 bg-blue-200 rounded-xl">
        {{ note.notetype }}
      </label>
    </div>

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-normal mb-3" for="note">
        BRANCH
      </label>  
      <label class="note flex-1 px-4 py-3 bg-blue-200 rounded-xl">
        {{ note.location }}
      </label>
    </div>

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-normal mb-3" for="note">
        CLIENT
      </label>  
      <label class="note flex-1 px-4 py-3 bg-blue-200 rounded-xl">
        {{ note.client }}
      </label>
    </div>

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-normal mb-3" for="note">
        NO.
      </label>  
      <label class="note flex-1 px-4 py-3 bg-blue-200 rounded-xl">
        {{ note.notekey }}
      </label>
    </div>

  </div>

  <div class="w-6/7 my-6 mx-auto p-2 lg:p-1 bg-white rounded-xl">
    <form class="flex mb-6 space-x-4">

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold" for="product">
        PRODUCT
      </label>      
      <select
          id="productlist" name="product" hx-trigger="change" hx-get="invlist/{{ note.id }}/" hx-target="#invlist" placeholder="Product" class="product flex-1 px-4 py-3 bg-gray-200 rounded-xl"/>
          <option value="">Product</option>
          {% for product in products %}
            <option value="{{ product.id}}">{{ product.product_name }} {{ product.carat.carat }}</option>
          {% endfor %}
      </select>
    </div>

      {% if note.notetype_id == 2 or note.notetype_id == 4 %}

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold" for="weight">
        WEIGHT
      </label>
      <select
          id="invlist" name="weight" placeholder="Available Items Weight" class="weight flex-1 px-4 py-3 bg-gray-200 rounded-xl"
          hx-trigger="change" hx-post="icost/{{ note.id }}/" hx-target="#invlist"/>
        <option value="">Available Items Weight</option>
      </select>
    </div>
      {% else %}

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold" for="weight">
        WEIGHT
      </label>
      <input
       id="invlist"
        hx-trigger="change" hx-post="icost/{{ note.id }}/" hx-target="#invlist"
        type="number"
        name="weight"
        value="1.00"
        step=".01"
        class="weight flex-1 px-4 py-3 bg-gray-200 rounded-xl"
        placeholder="weight"
      />
    </div>
      {% endif %}

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold" for="prodcost">
        RATE
      </label>      
      <input
      id="prodcost"
        hx-trigger="change" hx-post="icost/{{ note.id }}/" hx-target="#prodcost"
        type="number"
        name="prodcost"
        value="{{prodcost}}"
        step=".01"
        class="prodcost flex-1 px-4 py-3 bg-gray-200 rounded-xl"
        placeholder="{{prodcost}}"
      />
    </div>

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold" for="qty">
        QUANTITY
      </label> 
      <input
      id="qty"
        hx-trigger="change" hx-post="icost/{{ note.id }}/" hx-target="#invlist"
        type="number"
        name="qty"
        value="1"
        class="qty flex-1 px-4 py-3 bg-gray-200 rounded-xl"
        placeholder="qty"
      />
    </div>

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold" for="icost">
        COST
      </label>     
      <input
      id="icost"
        hx-trigger="change" hx-post="icost/{{ note.id }}/" hx-target="#invlist"
        type="number"
        name="icost"
        value="{{icost}}"
        class="cost flex-1 px-4 py-3 bg-gray-200 rounded-xl"
        placeholder="{{icost}}"
        disabled="true"
      /> 
    </div>

      {% if note.status_id == 0 %}

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold" for="add">
        ADD
      </label>       
      <button
        hx-post="{% url 'note:add_noteitem' note.id %}"
        hx-target="#noteitemlist"
        hx-swap="afterend"
        class="p-3 rounded-xl text-white bg-gray-400 hover:bg-gray-600"
      >
        +
      </button>
    </div>

    {% endif %}

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold" for="exit">
        EXIT
      </label>  
      <button
        {% comment %} hx-get="{% url 'notescopy' %}" {% endcomment %}
        class="p-3 rounded-xl text-white bg-red-500 hover:bg-red-600"
        hx-target="#noteitems"
      >
        X
      </button>
    </div>

    </form>
    <div class="flex py-3 rounded-xl bg-gray-100">
      <div class="w-4/5">
        <p class="px-6 text-xs font-medium text-gray-500 uppercase">Title</p>
      </div>

          <div class="w-4/5" id="message">
          {% if message is not None %}
              <p class ="px-6 text-xs font-medium text-gray-500 uppercase">{{message}}</p>
          {% endif %}
          </div>

        {% comment %} {%  include 'note/partials/message.html' %} {% endcomment %}
        {% comment %} <p class="px-6 text-xs font-medium text-gray-500 uppercase">{{message}}</p> {% endcomment %}
      <div class="hidden md:block w-1/5 px-6 text-right">
        <p class="text-xs font-medium text-gray-500 uppercase">Actions</p>
      </div>
    </div>

    <div class="divide-y divide-gray-200" id="noteitemlist">
      {% for noteitem in noteitems %} {% include 'note/partials/noteitem.html' %} {% endfor %}
    </div>
  </div>
</div>

templates/note/notes.html
      <div class="divide-y divide-gray-200" id="notes">
        {% for note in notes %} {% include 'note/partials/note.html' %} {%endfor %}
      </div>