core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'ERM Admin'
admin.site.index_title = 'Admin'
admin.site.site_title = 'ERM Admin'

urlpatterns = [
    path('', include('util.urls')),
    path('erm/', include('erm.urls')),
    path('note/', include('note.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

erm/urls.py
from django import views
from django.urls import path
from .views import *

app_name = 'erm'

urlpatterns = [
     path('product_list/', ProductListView.as_view(), name='product-list'),
     path('product_create/', ProductCreateView.as_view(), name='product-create'),
     path('product_detail/<int:pk>', ProductDetailView.as_view(), name='product-detail'),
     path('product_update/<int:pk>', ProductUpdateView.as_view(), name='product-update'),
     path('product_delete/<int:pk>', ProductDeleteView.as_view(), name='product-delete'),
     path('cost_list/', CostListView.as_view(), name='cost-list'),
     path('cost_create/', CostCreateView.as_view(), name='cost-create'),
     path('cost_detail/<int:pk>', CostDetailView.as_view(), name='cost-detail'),
     path('cost_update/<int:pk>', CostUpdateView.as_view(), name='cost-update'),
     path('cost_delete/<int:pk>', CostDeleteView.as_view(), name='cost-delete'),
     path('note_list/', notelist, name='notelist'),
     path('note_list/noteitemslist/<int:pk>', noteitemslist, name='noteitemslist'),
     path('note_list/noteitemslist_delete/<int:pk>', noteitemslist_delete, name='noteitemslist-delete'),
     path('note_list_rep/', notelistrep, name='notelist-rep'),
     # path('po/', POCreate, name='po-create'),
     #path('po_list/', POListView.as_view(), name='po-list'),
     #path('po_create/', poc, name='create-po'),
     #path('htmx/poitem-form/', create_poitem_form, name="poitem-form"),
     #path('htmx/poitem/<int:pk>/', detail_poitem, name="detail-poitem"),
     #path('htmx/poitem/<int:pk>/delete/', delete_poitem, name="delete-poitem"),
     #path('htmx/poitem/<int:pk>/update/', update_poitem, name="update-poitem"),
     #path('<int:pk>/', create_poitem, name="create-poitem"),
     # path('doc_list/', DocListView.as_view(), name='doc-list'),
     # path('doc_create/', doc_create, name='doc-create'),
     # path('docitem-form/', create_docitem_form, name="docitem-form"),
     # path('docitem/<int:pk>/', docitem_create, name="docitem-create"),
     # path('docitem/<int:pk>/detail', detail_docitem, name="detail-docitem"),
     # path('docitem/<int:pk>/list', docitem_list, name="list-docitem"),
     # path('docitem/<int:pk>/delete/', delete_docitem, name="delete-docitem"),
     # path('docitem/<int:pk>/update/', update_docitem, name="update-docitem"),
     
]

note/urls.py
from django.urls import path

from note.views import init, notes, noteitems, add_note, update_note, delete_note, add_noteitem, update_noteitem, delete_noteitem, edit_noteitem, invlist, icost

app_name = 'note'

urlpatterns = [
    path('', init, name='init'),
    path('notes/', notes, name='notes'),
    path('add-note/', add_note, name='add_note'),       
    path('update_note/<int:pk>/', update_note, name='update_note'),
    path('delete_note/<int:pk>/', delete_note, name='delete_note'),
    path('noteitems/<int:pk>/', noteitems, name='noteitems'),
    path('<int:note>/add-noteitem/', add_noteitem, name='add_noteitem'),
    path('update_noteitem/<int:pk>/', update_noteitem, name='update_noteitem'),
    path('delete_noteitem/<int:pk>/', delete_noteitem, name='delete_noteitem'),
    path('edit_noteitem/<int:pk>/', edit_noteitem, name='edit_noteitem'),
    path('invlist/<int:pk>/', invlist, name='invlist'),
    # path('invdata/', invdata, name='invdata'),
    # path('val_cost/', val_cost, name='val_cost'),
    # path('val_qty/', val_qty, name='val_qty'),
    path('icost/<int:pk>/', icost, name='icost'),
]

util/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.i18n import JavaScriptCatalog
from .views import LandingPageView, ActivateAccount, SignupView, Signup, activate

app_name = 'util'

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing-page'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    #path('signup/', Signup, name='signup'),
    #path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('reset-password/', PasswordResetView.as_view(success_url=reverse_lazy('util:password_reset_done')), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(success_url=reverse_lazy('util:password_reset_complete')), name='password_reset_confirm'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E R M</title>
    <link href="{% static 'tailwind.css' %}" rel="stylesheet" />
    <link href="{% static 'js/add.html' %}" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <script src="{% static 'htmx.min.js' %}"></script>
    <style></style>
  </head>
  <body>
    <div class="max-w-7xl max-auto">{% include 'navbar.html' %}</div>
    <div class="max-w-7xl max-auto">{% include 'err-msg.html' %}</div>
    <div class="py-5 px-4 sm:px-6 max-w-1xl mx-auto">
      {% block content %} {% endblock content %}
    </div>
    <script>
      document.body.addEventListener("htmx:configRequest", (event) => {
        event.detail.headers["X-CSRFToken"] = "{{ csrf_token }}";
      });
    </script>
  </body>
</html>

templates/err-msg.html
<div id="alerts" class="px-6 text-xs font-bold text-red-500 uppercase">
   <p> - {{msg}}</p> 
</div>

templates/landing_page.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="text-gray-600 body-font">
  <div
    class="container mx-auto flex px-0 py-0 items-center justify-center flex-col"
  >
    <img
      class="lg:w-2/6 md:w-3/6 w-5/6 mt-10 mb-10 object-cover object-center rounded"
      alt="erm_intro"
      src="{% static 'erm_intro.png' %}"
    />
    <!-- <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600"> -->
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"
      >
        Enterprise Resource Management
      </h1>
      <p class="mb-8 leading-relaxed">Project based on Jewelry Merchant</p>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar copy.html
<header class="text-gray-700 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">ERM</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% comment %} {% if request.user.is_authenticated and user.is_active %} {% endcomment %}
        {% if request.user.is_active %}
        <a href="{% url 'erm:product-list' %}" class="mr-5 hover:text-gray-900">Products</a> 
        <a href="{% url 'erm:cost-list' %}" class="mr-5 hover:text-gray-900">Cost</a> 
        <a href="{% url 'erm:note-list' %}" class="mr-5 hover:text-gray-900">Note-Report</a> 
        <a href="{% url 'note:init' %}" class="mr-5 hover:text-gray-900">Notes</a> 
        {% endif %}
        {% if not request.user.is_authenticated %} 
        <a href="{% url 'util:signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
        {% endif %}
      {% if request.user.is_authenticated %}
       Hi {{ request.user.username }}
         <a href="{% url 'util:logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-0 md:mt-0">Logout
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>

      {% else %}
        <a href="{% url 'util:login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-0 md:mt-0">Login
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
      {% endif %}
            </nav>
    </div>
  </section>

templates/navbar.html
<header class="text-gray-700 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">ERM</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% comment %} {% if request.user.is_authenticated and user.is_active %} {% endcomment %}
          {% if request.user.is_authenticated and request.user.is_active %}
            <a href="{% url 'erm:product-list' %}" class="mr-5 hover:text-gray-900">Products</a> 
            <a href="{% url 'erm:cost-list' %}" class="mr-5 hover:text-gray-900">Cost</a> 
            <a href="{% url 'erm:notelist' %}" class="mr-5 hover:text-gray-900">Note-Report</a> 
            <a href="{% url 'note:init' %}" class="mr-5 hover:text-gray-900">Notes</a> 
            Hi {{ request.user.username }}
            <a href="{% url 'util:logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-0 md:mt-0">Logout
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          {% else %}
            <a href="{% url 'util:signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
            <a href="{% url 'util:login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-0 md:mt-0">Login
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          {% endif %}
      </nav>
    </div>
  </section>